# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  branches:
    include:
    - dev
    - master
  paths:
    exclude:
     - README.md

pr:
  branches:
    include:
    - dev
    - master
  paths:
    exclude:
     - README.md

name: $(Build.BuildId)

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: Use NetCore 3.0.100-preview4-010538
  inputs:
    version: '3.0.100-preview4-010538'

- task: NuGetToolInstaller@0
  displayName: Use NuGet 4.9.2
  inputs:
    versionSpec: 4.9.2

- powershell: iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/onovotny/UpdateVsOnAgent/master/Fix-VisualStudioPreviewNuGetSdk.ps1'))
  displayName: VS Preview workaround

#- task: NuGetCommand@2
#  displayName: 'NuGet restore'
#  inputs:
#    restoreSolution: '$(solution)'
#    noCache: true
#    verbosityRestore: Detailed

#- task: VSBuild@1
#  inputs:
#    solution: '$(solution)'
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

- powershell: .\src\build.ps1 -Script .\src\build.cake -target appveyor
  displayName: 'Build with cake'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\src\Publish'
    Contents: |
     **
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: false

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
