# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  branches:
    include:
    - dev
    - master
  paths:
    exclude:
     - README.md
     - appveyor.yml

pr:
  branches:
    include:
    - dev
    - master
  paths:
    exclude:
     - README.md
     - appveyor.yml

name: $(Build.BuildId)

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: Install NetCore 3.0.100-preview6-012264
  inputs:
    version: '3.0.100-preview6-012264'

- task: NuGetToolInstaller@0
  displayName: Use NuGet 5.0.2
  inputs:
    versionSpec: 5.0.2

- powershell: .\build\Install-WindowsSDK.ps1
  displayName: Install Windows SDK 10.0.16299.91

- powershell: .\src\build.ps1 -Script .\src\build.cake --bootstrap
  displayName: 'Build: cake (bootstrap)'

- powershell: .\src\build.ps1 -Script .\src\build.cake -target appveyor
  displayName: 'Build: cake'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\src\Publish'
    Contents: |
     **
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: false

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: Package

- task: NuGetCommand@2
  displayName: Publish to internal nuget feed
  inputs:
    command: push
    nuGetFeedType: internal
    publishVstsFeed: MahApps.Metro.IconPacks
